spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
      - id: artist-service       # Id can be anything
        uri: lb://ARTIST-SERVICE  # give the same name as Appilication name 
        predicates:
        - Path=/artist       # Give Api path Name
      - id: identity-service
        uri: lb://IDENTITY-SERVICE
        predicates:
        - Path=/auth
      - id: bankservice
        uri: lb://bank-service
        predicates:
        - Path=/account
      - id: sponserserv
        uri: lb://sponsor-service
        predicates:
        - Path=/sponsor
  application:
    name: CLOUD-API-GATEWAY
        
server:
  port: 2222

